version: "3.9"
services:
  postgres:
    image: postgres:15.3
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_HOST: ${DB_HOST}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    hostname: postgres  # Устанавливаем имя хоста для контейнера
volumes:
  pgdata: